<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE charlist
[
<!ELEMENT charlist (character)>
<!ELEMENT character (latex,mathlatex,abbrev)>
<!ELEMENT latex (#PCDATA)>
<!ELEMENT mathlatex (#PCDATA)>
<!ELEMENT abbrev (#PCDATA)>
]>
<charlist>
<character id="32" mode="text" type="other">
<latex>\space </latex>
</character>

<character id="33" mode="text" type="punctuation">
<latex>!</latex>
</character>

<character id="34" mode="text" type="other">
<latex>"</latex>
</character>

<character id="35" mode="text" type="normal">
<latex>\#</latex>
</character>

<character id="36" mode="mixed" type="normal">
<latex>\textdollar </latex>
<mathlatex>\$</mathlatex>
</character>

<character id="37" mode="text" type="normal">
<latex>\%</latex>
</character>

<character id="38" mode="text" type="other">
<latex>\&amp;</latex>
</character>

<character id="39" mode="text" type="other">
<latex>\textquotesingle </latex>
</character>

<character id="40" mode="text" type="opening">
<latex>(</latex>
</character>

<character id="41" mode="text" type="closing">
<latex>)</latex>
</character>

<character id="42" mode="math" type="other">
<latex>\ast </latex>
</character>

<character id="43" mode="math" type="binaryop">
<latex>+</latex>
</character>

<character id="44" mode="text" type="punctuation">
<latex>,</latex>
</character>

<character id="45" mode="math" type="other">
<latex>-</latex>
</character>

<character id="46" mode="text" type="punctuation">
<latex>.</latex>
</character>

<character id="47" mode="text" type="other">
<latex>/</latex>
</character>

<character id="48" mode="text" type="other">
<latex>0</latex>
</character>

<character id="49" mode="text" type="other">
<latex>1</latex>
</character>

<character id="50" mode="text" type="other">
<latex>2</latex>
</character>

<character id="51" mode="text" type="other">
<latex>3</latex>
</character>

<character id="52" mode="text" type="other">
<latex>4</latex>
</character>

<character id="53" mode="text" type="other">
<latex>5</latex>
</character>

<character id="54" mode="text" type="other">
<latex>6</latex>
</character>

<character id="55" mode="text" type="other">
<latex>7</latex>
</character>

<character id="56" mode="text" type="other">
<latex>8</latex>
</character>

<character id="57" mode="text" type="other">
<latex>9</latex>
</character>

<character id="58" mode="text" type="punctuation">
<latex>:</latex>
</character>

<character id="59" mode="math" type="punctuation">
<latex>;</latex>
</character>

<character id="60" mode="math" type="relation">
<latex>&lt;</latex>
</character>

<character id="61" mode="text" type="relation">
<latex>=</latex>
</character>

<character id="62" mode="math" type="relation">
<latex>&gt;</latex>
</character>

<character id="63" mode="text" type="punctuation">
<latex>?</latex>
</character>

<character id="64" mode="text" type="normal">
<latex>@</latex>
</character>

<character id="65" mode="text" type="other">
<latex>A</latex>
</character>

<character id="66" mode="text" type="other">
<latex>B</latex>
</character>

<character id="67" mode="text" type="other">
<latex>C</latex>
</character>

<character id="68" mode="text" type="other">
<latex>D</latex>
</character>

<character id="69" mode="text" type="other">
<latex>E</latex>
</character>

<character id="70" mode="text" type="other">
<latex>F</latex>
</character>

<character id="71" mode="text" type="other">
<latex>G</latex>
</character>

<character id="72" mode="text" type="other">
<latex>H</latex>
</character>

<character id="73" mode="text" type="other">
<latex>I</latex>
</character>

<character id="74" mode="text" type="other">
<latex>J</latex>
</character>

<character id="75" mode="text" type="other">
<latex>K</latex>
</character>

<character id="76" mode="text" type="other">
<latex>L</latex>
</character>

<character id="77" mode="text" type="other">
<latex>M</latex>
</character>

<character id="78" mode="text" type="other">
<latex>N</latex>
</character>

<character id="79" mode="text" type="other">
<latex>O</latex>
</character>

<character id="80" mode="text" type="other">
<latex>P</latex>
</character>

<character id="81" mode="text" type="other">
<latex>Q</latex>
</character>

<character id="82" mode="text" type="other">
<latex>R</latex>
</character>

<character id="83" mode="text" type="other">
<latex>S</latex>
</character>

<character id="84" mode="text" type="other">
<latex>T</latex>
</character>

<character id="85" mode="text" type="other">
<latex>U</latex>
</character>

<character id="86" mode="text" type="other">
<latex>V</latex>
</character>

<character id="87" mode="text" type="other">
<latex>W</latex>
</character>

<character id="88" mode="text" type="other">
<latex>X</latex>
</character>

<character id="89" mode="text" type="other">
<latex>Y</latex>
</character>

<character id="90" mode="text" type="other">
<latex>Z</latex>
</character>

<character id="91" mode="text" type="opening">
<latex>[</latex>
</character>

<character id="92" mode="mixed" type="normal">
<latex>\textbackslash </latex>
<mathlatex>\backslash </mathlatex>
</character>

<character id="93" mode="text" type="closing">
<latex>]</latex>
</character>

<character id="94" mode="text" type="other">
<latex>\^{}</latex>
</character>

<character id="95" mode="math" type="other">
<latex>\_</latex>
</character>

<character id="96" mode="text" type="other">
<latex>\textasciigrave </latex>
</character>

<character id="97" mode="text" type="other">
<latex>a</latex>
</character>

<character id="98" mode="text" type="other">
<latex>b</latex>
</character>

<character id="99" mode="text" type="other">
<latex>c</latex>
</character>

<character id="100" mode="text" type="other">
<latex>d</latex>
</character>

<character id="101" mode="text" type="other">
<latex>e</latex>
</character>

<character id="102" mode="text" type="other">
<latex>f</latex>
</character>

<character id="103" mode="text" type="other">
<latex>g</latex>
</character>

<character id="104" mode="text" type="other">
<latex>h</latex>
</character>

<character id="105" mode="text" type="other">
<latex>i</latex>
</character>

<character id="106" mode="text" type="other">
<latex>j</latex>
</character>

<character id="107" mode="text" type="other">
<latex>k</latex>
</character>

<character id="108" mode="text" type="other">
<latex>l</latex>
</character>

<character id="109" mode="text" type="other">
<latex>m</latex>
</character>

<character id="110" mode="text" type="other">
<latex>n</latex>
</character>

<character id="111" mode="text" type="other">
<latex>o</latex>
</character>

<character id="112" mode="text" type="other">
<latex>p</latex>
</character>

<character id="113" mode="text" type="other">
<latex>q</latex>
</character>

<character id="114" mode="text" type="other">
<latex>r</latex>
</character>

<character id="115" mode="text" type="other">
<latex>s</latex>
</character>

<character id="116" mode="text" type="other">
<latex>t</latex>
</character>

<character id="117" mode="text" type="other">
<latex>u</latex>
</character>

<character id="118" mode="text" type="other">
<latex>v</latex>
</character>

<character id="119" mode="text" type="other">
<latex>w</latex>
</character>

<character id="120" mode="text" type="other">
<latex>x</latex>
</character>

<character id="121" mode="text" type="other">
<latex>y</latex>
</character>

<character id="122" mode="text" type="other">
<latex>z</latex>
</character>

<character id="123" mode="math" type="opening">
<latex>\lbrace </latex>
</character>

<character id="124" mode="math" type="other">
<latex>\vert </latex>
</character>

<character id="125" mode="math" type="closing">
<latex>\rbrace </latex>
</character>

<character id="126" mode="text" type="other">
<latex>\textasciitilde </latex>
</character>

<character id="160" mode="math" type="other">
<latex>~</latex>
</character>

<character id="161" mode="text" type="punctuation">
<latex>\textexclamdown </latex>
</character>

<character id="162" mode="mixed" type="normal">
<latex>\textcent </latex>
<mathlatex>\mbox{\textcent}</mathlatex>
</character>

<character id="163" mode="mixed" type="normal">
<latex>\textsterling </latex>
<mathlatex>\pounds </mathlatex>
</character>

<character id="164" mode="mixed" type="normal">
<latex>\textcurrency </latex>
<mathlatex>\mbox{\textcurrency}</mathlatex>
</character>

<character id="165" mode="mixed" type="normal">
<latex>\textyen </latex>
<mathlatex>\yen </mathlatex>
</character>

<character id="166" mode="text" type="normal">
<latex>\textbrokenbar </latex>
</character>

<character id="167" mode="mixed" type="normal">
<latex>\textsection </latex>
<mathlatex>\S </mathlatex>
</character>

<character id="168" mode="text" type="other">
<latex>\textasciidieresis </latex>
</character>

<character id="169" mode="mixed" type="normal">
<latex>\textcopyright </latex>
<mathlatex>\copyright </mathlatex>
</character>

<character id="170" mode="text" type="other">
<latex>\textordfeminine </latex>
</character>

<character id="171" mode="mixed" type="opening">
<latex>\guillemotleft </latex>
<mathlatex>\mbox{\guillemotleft}</mathlatex>
</character>

<character id="172" mode="math" type="normal">
<latex>\lnot </latex>
</character>

<character id="173" mode="math" type="other">
<latex>\-</latex>
</character>

<character id="174" mode="mixed" type="normal">
<latex>\textregistered </latex>
<mathlatex>\circledR </mathlatex>
</character>

<character id="175" mode="text" type="other">
<latex>\textasciimacron </latex>
</character>

<character id="176" mode="mixed" type="other">
<latex>\textdegree </latex>
<mathlatex>\mbox{\textdegree}</mathlatex>
</character>

<character id="177" mode="math" type="binaryop">
<latex>\pm </latex>
</character>

<character id="178" mode="math" type="other">
<latex>{^2}</latex>
</character>

<character id="179" mode="math" type="other">
<latex>{^3}</latex>
</character>

<character id="180" mode="text" type="other">
<latex>\textasciiacute </latex>
</character>

<character id="181" mode="math" type="normal">
<latex>\mathrm{\mu}</latex>
</character>

<character id="182" mode="mixed" type="normal">
<latex>\textparagraph </latex>
<mathlatex>\P </mathlatex>
</character>

<character id="183" mode="math" type="binaryop">
<latex>\cdot </latex>
</character>

<character id="184" mode="mixed" type="other">
<latex>\c{}</latex>
<mathlatex>\mbox{\c{}}</mathlatex>
</character>

<character id="185" mode="math" type="other">
<latex>{^1}</latex>
</character>

<character id="186" mode="text" type="other">
<latex>\textordmasculine </latex>
</character>

<character id="187" mode="mixed" type="closing">
<latex>\guillemotright </latex>
<mathlatex>\mbox{\guillemotright}</mathlatex>
</character>

<character id="188" mode="text" type="other">
<latex>\textonequarter </latex>
</character>

<character id="189" mode="text" type="other">
<latex>\textonehalf </latex>
</character>

<character id="190" mode="text" type="other">
<latex>\textthreequarters </latex>
</character>

<character id="191" mode="text" type="punctuation">
<latex>\textquestiondown </latex>
</character>

<character id="192" mode="mixed" type="other">
<latex>\`{A}</latex>
<mathlatex>\grave{A}</mathlatex>
<abbrev>A</abbrev>
</character>

<character id="193" mode="mixed" type="other">
<latex>\'{A}</latex>
<mathlatex>\acute{A}</mathlatex>
<abbrev>A</abbrev>
</character>

<character id="194" mode="mixed" type="other">
<latex>\^{A}</latex>
<mathlatex>\hat{A}</mathlatex>
<abbrev>A</abbrev>
</character>

<character id="195" mode="mixed" type="other">
<latex>\~{A}</latex>
<mathlatex>\tilde{A}</mathlatex>
<abbrev>A</abbrev>
</character>

<character id="196" mode="mixed" type="other">
<latex>\"{A}</latex>
<mathlatex>\ddot{A}</mathlatex>
<abbrev>A</abbrev>
</character>

<character id="197" mode="text" type="other">
<latex>\AA </latex>
</character>

<character id="198" mode="text" type="alphabetic">
<latex>\AE </latex>
<abbrev>AE</abbrev>
</character>

<character id="199" mode="mixed" type="other">
<latex>\c{C}</latex>
<mathlatex>\mbox{\c{C}}</mathlatex>
<abbrev>C</abbrev>
</character>

<character id="200" mode="mixed" type="other">
<latex>\`{E}</latex>
<mathlatex>\grave{E}</mathlatex>
<abbrev>E</abbrev>
</character>

<character id="201" mode="mixed" type="other">
<latex>\'{E}</latex>
<mathlatex>\acute{E}</mathlatex>
<abbrev>E</abbrev>
</character>

<character id="202" mode="mixed" type="other">
<latex>\^{E}</latex>
<mathlatex>\hat{E}</mathlatex>
<abbrev>E</abbrev>
</character>

<character id="203" mode="mixed" type="other">
<latex>\"{E}</latex>
<mathlatex>\ddot{E}</mathlatex>
<abbrev>E</abbrev>
</character>

<character id="204" mode="mixed" type="other">
<latex>\`{I}</latex>
<mathlatex>\grave{I}</mathlatex>
<abbrev>I</abbrev>
</character>

<character id="205" mode="mixed" type="other">
<latex>\'{I}</latex>
<mathlatex>\acute{I}</mathlatex>
<abbrev>I</abbrev>
</character>

<character id="206" mode="mixed" type="other">
<latex>\^{I}</latex>
<mathlatex>\hat{I}</mathlatex>
<abbrev>I</abbrev>
</character>

<character id="207" mode="mixed" type="other">
<latex>\"{I}</latex>
<mathlatex>\ddot{I}</mathlatex>
<abbrev>I</abbrev>
</character>

<character id="208" mode="text" type="alphabetic">
<latex>\DH </latex>
<abbrev>D</abbrev>
</character>

<character id="209" mode="mixed" type="other">
<latex>\~{N}</latex>
<mathlatex>\tilde{N}</mathlatex>
<abbrev>N</abbrev>
</character>

<character id="210" mode="mixed" type="other">
<latex>\`{O}</latex>
<mathlatex>\grave{O}</mathlatex>
<abbrev>O</abbrev>
</character>

<character id="211" mode="mixed" type="other">
<latex>\'{O}</latex>
<mathlatex>\acute{O}</mathlatex>
<abbrev>O</abbrev>
</character>

<character id="212" mode="mixed" type="other">
<latex>\^{O}</latex>
<mathlatex>\hat{O}</mathlatex>
<abbrev>O</abbrev>
</character>

<character id="213" mode="mixed" type="other">
<latex>\~{O}</latex>
<mathlatex>\tilde{O}</mathlatex>
<abbrev>O</abbrev>
</character>

<character id="214" mode="mixed" type="other">
<latex>\"{O}</latex>
<mathlatex>\ddot{O}</mathlatex>
<abbrev>O</abbrev>
</character>

<character id="215" mode="mixed" type="binaryop">
<latex>\texttimes </latex>
<mathlatex>\times </mathlatex>
</character>

<character id="216" mode="text" type="alphabetic">
<latex>\O </latex>
<abbrev>O</abbrev>
</character>

<character id="217" mode="mixed" type="other">
<latex>\`{U}</latex>
<mathlatex>\grave{U}</mathlatex>
<abbrev>U</abbrev>
</character>

<character id="218" mode="mixed" type="other">
<latex>\'{U}</latex>
<mathlatex>\acute{U}</mathlatex>
<abbrev>U</abbrev>
</character>

<character id="219" mode="mixed" type="other">
<latex>\^{U}</latex>
<mathlatex>\hat{U}</mathlatex>
<abbrev>U</abbrev>
</character>

<character id="220" mode="mixed" type="other">
<latex>\"{U}</latex>
<mathlatex>\ddot{U}</mathlatex>
<abbrev>U</abbrev>
</character>

<character id="221" mode="mixed" type="other">
<latex>\'{Y}</latex>
<mathlatex>\acute{Y}</mathlatex>
<abbrev>Y</abbrev>
</character>

<character id="222" mode="text" type="alphabetic">
<latex>\TH </latex>
<abbrev>P</abbrev>
</character>

<character id="223" mode="text" type="alphabetic">
<latex>\ss </latex>
<abbrev>ss</abbrev>
</character>

<character id="224" mode="mixed" type="other">
<latex>\`{a}</latex>
<mathlatex>\grave{a}</mathlatex>
<abbrev>a</abbrev>
</character>

<character id="225" mode="mixed" type="other">
<latex>\'{a}</latex>
<mathlatex>\acute{a}</mathlatex>
<abbrev>a</abbrev>
</character>

<character id="226" mode="mixed" type="other">
<latex>\^{a}</latex>
<mathlatex>\hat{a}</mathlatex>
<abbrev>a</abbrev>
</character>

<character id="227" mode="mixed" type="other">
<latex>\~{a}</latex>
<mathlatex>\tilde{a}</mathlatex>
<abbrev>a</abbrev>
</character>

<character id="228" mode="mixed" type="other">
<latex>\"{a}</latex>
<mathlatex>\ddot{a}</mathlatex>
<abbrev>a</abbrev>
</character>

<character id="229" mode="text" type="other">
<latex>\aa </latex>
<abbrev>a</abbrev>
</character>

<character id="230" mode="text" type="alphabetic">
<latex>\ae </latex>
<abbrev>ae</abbrev>
</character>

<character id="231" mode="mixed" type="alphabetic">
<latex>\c{c}</latex>
<mathlatex>\mbox{\c{c}}</mathlatex>
<abbrev>c</abbrev>
</character>

<character id="232" mode="mixed" type="other">
<latex>\`{e}</latex>
<mathlatex>\grave{e}</mathlatex>
<abbrev>e</abbrev>
</character>

<character id="233" mode="mixed" type="other">
<latex>\'{e}</latex>
<mathlatex>\acute{e}</mathlatex>
<abbrev>e</abbrev>
</character>

<character id="234" mode="mixed" type="other">
<latex>\^{e}</latex>
<mathlatex>\hat{e}</mathlatex>
<abbrev>e</abbrev>
</character>

<character id="235" mode="mixed" type="other">
<latex>\"{e}</latex>
<mathlatex>\ddot{e}</mathlatex>
<abbrev>e</abbrev>
</character>

<character id="236" mode="mixed" type="other">
<latex>\`{\i}</latex>
<mathlatex>\grave{\imath}</mathlatex>
<abbrev>i</abbrev>
</character>

<character id="237" mode="mixed" type="other">
<latex>\'{\i}</latex>
<mathlatex>\acute{\imath}</mathlatex>
<abbrev>i</abbrev>
</character>

<character id="238" mode="mixed" type="other">
<latex>\^{\i}</latex>
<mathlatex>\hat{\imath}</mathlatex>
<abbrev>i</abbrev>
</character>

<character id="239" mode="mixed" type="other">
<latex>\"{\i}</latex>
<mathlatex>\ddot{\imath}</mathlatex>
<abbrev>i</abbrev>
</character>

<character id="240" mode="text" type="alphabetic">
<latex>\dh </latex>
<abbrev>d</abbrev>
</character>

<character id="241" mode="mixed" type="alphabetic">
<latex>\~{n}</latex>
<mathlatex>\tilde{n}</mathlatex>
<abbrev>n</abbrev>
</character>

<character id="242" mode="mixed" type="other">
<latex>\`{o}</latex>
<mathlatex>\grave{o}</mathlatex>
<abbrev>o</abbrev>
</character>

<character id="243" mode="mixed" type="other">
<latex>\'{o}</latex>
<mathlatex>\acute{o}</mathlatex>
<abbrev>o</abbrev>
</character>

<character id="244" mode="mixed" type="other">
<latex>\^{o}</latex>
<mathlatex>\hat{o}</mathlatex>
<abbrev>o</abbrev>
</character>

<character id="245" mode="mixed" type="other">
<latex>\~{o}</latex>
<mathlatex>\tilde{o}</mathlatex>
<abbrev>o</abbrev>
</character>

<character id="246" mode="mixed" type="other">
<latex>\"{o}</latex>
<mathlatex>\ddot{o}</mathlatex>
<abbrev>o</abbrev>
</character>

<character id="247" mode="math" type="binaryop">
<latex>\div </latex>
</character>

<character id="248" mode="text" type="alphabetic">
<latex>\o </latex>
<abbrev>o</abbrev>
</character>

<character id="249" mode="mixed" type="other">
<latex>\`{u}</latex>
<mathlatex>\grave{u}</mathlatex>
<abbrev>u</abbrev>
</character>

<character id="250" mode="mixed" type="other">
<latex>\'{u}</latex>
<mathlatex>\acute{u}</mathlatex>
<abbrev>u</abbrev>
</character>

<character id="251" mode="mixed" type="other">
<latex>\^{u}</latex>
<mathlatex>\hat{u}</mathlatex>
<abbrev>u</abbrev>
</character>

<character id="252" mode="mixed" type="other">
<latex>\"{u}</latex>
<mathlatex>\ddot{u}</mathlatex>
<abbrev>u</abbrev>
</character>

<character id="253" mode="mixed" type="other">
<latex>\'{y}</latex>
<mathlatex>\acute{y}</mathlatex>
<abbrev>y</abbrev>
</character>

<character id="254" mode="text" type="alphabetic">
<latex>\th </latex>
<abbrev>p</abbrev>
</character>

<character id="255" mode="mixed" type="other">
<latex>\"{y}</latex>
<mathlatex>\ddot{y}</mathlatex>
<abbrev>y</abbrev>
</character>

<character id="256" mode="mixed" type="other">
<latex>\={A}</latex>
<mathlatex>\bar{A}</mathlatex>
<abbrev>A</abbrev>
</character>

<character id="257" mode="mixed" type="other">
<latex>\={a}</latex>
<mathlatex>\bar{a}</mathlatex>
<abbrev>a</abbrev>
</character>

<character id="258" mode="mixed" type="other">
<latex>\u{A}</latex>
<mathlatex>\breve{A}</mathlatex>
<abbrev>A</abbrev>
</character>

<character id="259" mode="mixed" type="other">
<latex>\u{a}</latex>
<mathlatex>\u{a}</mathlatex>
<abbrev>a</abbrev>
</character>

<character id="260" mode="text" type="other">
<latex>\k{A}</latex>
<abbrev>A</abbrev>
</character>

<character id="261" mode="text" type="other">
<latex>\k{a}</latex>
<abbrev>a</abbrev>
</character>

<character id="262" mode="mixed" type="other">
<latex>\'{C}</latex>
<mathlatex>\acute{C}</mathlatex>
<abbrev>C</abbrev>
</character>

<character id="263" mode="mixed" type="other">
<latex>\'{c}</latex>
<mathlatex>\acute{c}</mathlatex>
<abbrev>c</abbrev>
</character>

<character id="264" mode="mixed" type="other">
<latex>\^{C}</latex>
<mathlatex>\hat{C}</mathlatex>
<abbrev>C</abbrev>
</character>

<character id="265" mode="mixed" type="other">
<latex>\^{c}</latex>
<mathlatex>\hat{c}</mathlatex>
<abbrev>c</abbrev>
</character>

<character id="266" mode="mixed" type="other">
<latex>\.{C}</latex>
<mathlatex>\dot{C}</mathlatex>
<abbrev>C</abbrev>
</character>

<character id="267" mode="mixed" type="other">
<latex>\.{c}</latex>
<mathlatex>\dot{c}</mathlatex>
<abbrev>c</abbrev>
</character>

<character id="268" mode="mixed" type="other">
<latex>\v{C}</latex>
<mathlatex>\check{C}</mathlatex>
<abbrev>C</abbrev>
</character>

<character id="269" mode="mixed" type="alphabetic">
<latex>\v{c}</latex>
<mathlatex>\check{c}</mathlatex>
<abbrev>c</abbrev>
</character>

<character id="270" mode="mixed" type="other">
<latex>\v{D}</latex>
<mathlatex>\check{D}</mathlatex>
<abbrev>D</abbrev>
</character>

<character id="271" mode="mixed" type="other">
<latex>\v{d}</latex>
<mathlatex>\check{d}</mathlatex>
<abbrev>d</abbrev>
</character>

<character id="272" mode="text" type="alphabetic">
<latex>\DJ </latex>
<abbrev>D</abbrev>
</character>

<character id="273" mode="text" type="alphabetic">
<latex>\dj </latex>
<abbrev>d</abbrev>
</character>

<character id="274" mode="mixed" type="other">
<latex>\={E}</latex>
<mathlatex>\bar{E}</mathlatex>
<abbrev>E</abbrev>
</character>

<character id="275" mode="mixed" type="other">
<latex>\={e}</latex>
<mathlatex>\bar{e}</mathlatex>
<abbrev>e</abbrev>
</character>

<character id="276" mode="mixed" type="other">
<latex>\u{E}</latex>
<mathlatex>\breve{E}</mathlatex>
<abbrev>E</abbrev>
</character>

<character id="277" mode="mixed" type="other">
<latex>\u{e}</latex>
<mathlatex>\breve{e}</mathlatex>
<abbrev>e</abbrev>
</character>

<character id="278" mode="mixed" type="other">
<latex>\.{E}</latex>
<mathlatex>\dot{E}</mathlatex>
<abbrev>E</abbrev>
</character>

<character id="279" mode="mixed" type="other">
<latex>\.{e}</latex>
<mathlatex>\dot{e}</mathlatex>
<abbrev>e</abbrev>
</character>

<character id="280" mode="mixed" type="other">
<latex>\k{E}</latex>
<mathlatex>\k{E}</mathlatex>
<abbrev>E</abbrev>
</character>

<character id="281" mode="text" type="other">
<latex>\k{e}</latex>
<abbrev>e</abbrev>
</character>

<character id="282" mode="mixed" type="other">
<latex>\v{E}</latex>
<mathlatex>\check{E}</mathlatex>
<abbrev>E</abbrev>
</character>

<character id="283" mode="mixed" type="other">
<latex>\v{e}</latex>
<mathlatex>\check{e}</mathlatex>
<abbrev>e</abbrev>
</character>

<character id="284" mode="mixed" type="other">
<latex>\^{G}</latex>
<mathlatex>\hat{G}</mathlatex>
<abbrev>G</abbrev>
</character>

<character id="285" mode="mixed" type="other">
<latex>\^{g}</latex>
<mathlatex>\hat{g}</mathlatex>
<abbrev>g</abbrev>
</character>

<character id="286" mode="mixed" type="other">
<latex>\u{G}</latex>
<mathlatex>\breve{G}</mathlatex>
<abbrev>G</abbrev>
</character>

<character id="287" mode="mixed" type="other">
<latex>\u{g}</latex>
<mathlatex>\breve{g}</mathlatex>
<abbrev>g</abbrev>
</character>

<character id="288" mode="mixed" type="other">
<latex>\.{G}</latex>
<mathlatex>\dot{G}</mathlatex>
<abbrev>G</abbrev>
</character>

<character id="289" mode="mixed" type="other">
<latex>\.{g}</latex>
<mathlatex>\dot{g}</mathlatex>
<abbrev>g</abbrev>
</character>

<character id="290" mode="mixed" type="other">
<latex>\c{G}</latex>
<mathlatex>\mbox{\c{G}}</mathlatex>
<abbrev>G</abbrev>
</character>

<character id="291" mode="mixed" type="other">
<latex>\c{g}</latex>
<mathlatex>\mbox{\c{g}}</mathlatex>
<abbrev>g</abbrev>
</character>

<character id="292" mode="mixed" type="other">
<latex>\^{H}</latex>
<mathlatex>\hat{H}</mathlatex>
<abbrev>H</abbrev>
</character>

<character id="293" mode="mixed" type="other">
<latex>\^{h}</latex>
<mathlatex>\hat{h}</mathlatex>
<abbrev>h</abbrev>
</character>

<character id="294" mode="text" type="other">
<latex>{\fontencoding{LELA}\selectfont\char40}</latex>
</character>

<character id="295" mode="math" type="alphabetic">
<latex>\Elzxh </latex>
<abbrev>h</abbrev>
</character>

<character id="296" mode="mixed" type="other">
<latex>\~{I}</latex>
<mathlatex>\tilde{I}</mathlatex>
<abbrev>I</abbrev>
</character>

<character id="297" mode="mixed" type="other">
<latex>\~{\i}</latex>
<mathlatex>\tilde{\imath}</mathlatex>
</character>

<character id="298" mode="mixed" type="other">
<latex>\={I}</latex>
<mathlatex>\bar{I}</mathlatex>
<abbrev>I</abbrev>
</character>

<character id="299" mode="mixed" type="other">
<latex>\={\i}</latex>
<mathlatex>\bar{\imath}</mathlatex>
<abbrev>i</abbrev>
</character>

<character id="300" mode="mixed" type="other">
<latex>\u{I}</latex>
<mathlatex>\breve{I}</mathlatex>
<abbrev>I</abbrev>
</character>

<character id="301" mode="mixed" type="other">
<latex>\u{\i}</latex>
<mathlatex>\breve{\imath}</mathlatex>
<abbrev>i</abbrev>
</character>

<character id="302" mode="text" type="other">
<latex>\k{I}</latex>
<abbrev>I</abbrev>
</character>

<character id="303" mode="text" type="other">
<latex>\k{i}</latex>
<abbrev>i</abbrev>
</character>

<character id="304" mode="mixed" type="other">
<latex>\.{I}</latex>
<mathlatex>\dot{I}</mathlatex>
<abbrev>I</abbrev>
</character>

<character id="305" mode="mixed" type="alphabetic">
<latex>\i </latex>
<mathlatex>\imath </mathlatex>
<abbrev>i</abbrev>
</character>

<character id="306" mode="text" type="other">
<latex>IJ</latex>
</character>

<character id="307" mode="text" type="other">
<latex>ij</latex>
</character>

<character id="308" mode="mixed" type="other">
<latex>\^{J}</latex>
<mathlatex>\hat{J}</mathlatex>
<abbrev>J</abbrev>
</character>

<character id="309" mode="mixed" type="other">
<latex>\^{\j}</latex>
<mathlatex>\hat{\jmath}</mathlatex>
<abbrev>j</abbrev>
</character>

<character id="310" mode="mixed" type="other">
<latex>\c{K}</latex>
<mathlatex>\mbox{\c{K}}</mathlatex>
<abbrev>K</abbrev>
</character>

<character id="311" mode="mixed" type="other">
<latex>\c{k}</latex>
<mathlatex>\mbox{\c{k}}</mathlatex>
<abbrev>k</abbrev>
</character>

<character id="312" mode="text" type="other">
<latex>{\fontencoding{LELA}\selectfont\char91}</latex>
</character>

<character id="313" mode="mixed" type="other">
<latex>\'{L}</latex>
<mathlatex>\acute{L}</mathlatex>
<abbrev>L</abbrev>
</character>

<character id="314" mode="mixed" type="other">
<latex>\'{l}</latex>
<mathlatex>\acute{l}</mathlatex>
<abbrev>l</abbrev>
</character>

<character id="315" mode="mixed" type="other">
<latex>\c{L}</latex>
<mathlatex>\mbox{\c{L}}</mathlatex>
<abbrev>L</abbrev>
</character>

<character id="316" mode="mixed" type="other">
<latex>\c{l}</latex>
<mathlatex>\mbox{\c{l}}</mathlatex>
<abbrev>l</abbrev>
</character>

<character id="317" mode="mixed" type="other">
<latex>\v{L}</latex>
<mathlatex>\check{L}</mathlatex>
<abbrev>L</abbrev>
</character>

<character id="318" mode="mixed" type="other">
<latex>\v{l}</latex>
<mathlatex>\check{l}</mathlatex>
<abbrev>l</abbrev>
</character>

<character id="319" mode="text" type="other">
<latex>{\fontencoding{LELA}\selectfont\char201}</latex>
</character>

<character id="320" mode="text" type="other">
<latex>{\fontencoding{LELA}\selectfont\char202}</latex>
</character>

<character id="321" mode="text" type="alphabetic">
<latex>\L </latex>
<abbrev>L</abbrev>
</character>

<character id="322" mode="text" type="alphabetic">
<latex>\l </latex>
<abbrev>l</abbrev>
</character>

<character id="323" mode="mixed" type="other">
<latex>\'{N}</latex>
<mathlatex>\acute{N}</mathlatex>
<abbrev>N</abbrev>
</character>

<character id="324" mode="mixed" type="other">
<latex>\'{n}</latex>
<mathlatex>\acute{n}</mathlatex>
<abbrev>n</abbrev>
</character>

<character id="325" mode="mixed" type="other">
<latex>\c{N}</latex>
<mathlatex>\mbox{\c{N}}</mathlatex>
<abbrev>N</abbrev>
</character>

<character id="326" mode="mixed" type="other">
<latex>\c{n}</latex>
<mathlatex>\mbox{\c{n}}</mathlatex>
<abbrev>n</abbrev>
</character>

<character id="327" mode="mixed" type="other">
<latex>\v{N}</latex>
<mathlatex>\check{N}</mathlatex>
<abbrev>N</abbrev>
</character>

<character id="328" mode="mixed" type="other">
<latex>\v{n}</latex>
<mathlatex>\check{n}</mathlatex>
<abbrev>n</abbrev>
</character>

<character id="329" mode="text" type="other">
<latex>'n</latex>
</character>

<character id="330" mode="text" type="other">
<latex>\NG </latex>
<abbrev>N</abbrev>
</character>

<character id="331" mode="text" type="alphabetic">
<latex>\ng </latex>
<abbrev>n</abbrev>
</character>

<character id="332" mode="mixed" type="other">
<latex>\={O}</latex>
<mathlatex>\bar{O}</mathlatex>
<abbrev>O</abbrev>
</character>

<character id="333" mode="mixed" type="other">
<latex>\={o}</latex>
<mathlatex>\bar{o}</mathlatex>
<abbrev>o</abbrev>
</character>

<character id="334" mode="mixed" type="other">
<latex>\u{O}</latex>
<mathlatex>\breve{O}</mathlatex>
<abbrev>O</abbrev>
</character>

<character id="335" mode="mixed" type="other">
<latex>\u{o}</latex>
<mathlatex>\breve{o}</mathlatex>
<abbrev>o</abbrev>
</character>

<character id="336" mode="mixed" type="other">
<latex>\H{O}</latex>
<mathlatex>\mbox{\H{O}}</mathlatex>
<abbrev>O</abbrev>
</character>

<character id="337" mode="mixed" type="other">
<latex>\H{o}</latex>
<mathlatex>\mbox{\H{o}}</mathlatex>
<abbrev>o</abbrev>
</character>

<character id="338" mode="text" type="alphabetic">
<latex>\OE </latex>
<abbrev>OE</abbrev>
</character>

<character id="339" mode="text" type="alphabetic">
<latex>\oe </latex>
<abbrev>oe</abbrev>
</character>

<character id="340" mode="mixed" type="other">
<latex>\'{R}</latex>
<mathlatex>\acute{R}</mathlatex>
<abbrev>R</abbrev>
</character>

<character id="341" mode="mixed" type="other">
<latex>\'{r}</latex>
<mathlatex>\acute{r}</mathlatex>