<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE journallist
[
<!ELEMENT journallist (letter)>
<!ELEMENT letter (journal)>
<!ELEMENT journal (#PCDATA)>
]>
<journallist>
<letter id="2">
<journal ident="2D MATERIALS" abbrev="2D Mater."></journal>
</letter>
<letter id="3">
<journal ident="3 BIOTECH" abbrev="3 Biotech"></journal>
<journal ident="3D PRINTING AND ADDITIVE MANUFACTURING" abbrev="3D Print. Addit. Manuf."></journal>
<journal ident="3D PRINTING IN MEDICINE" abbrev="3D Print. Med."></journal>
</letter>
<letter id="5">
<journal ident="50TH ANNIVERSARY CRACOW UNIVERSITY OF TECHNOLOGY ANNIVERSARY ISSUE" abbrev="50th Anniv. Cracow Univ. Technol. Anniv. Issue"></journal>
</letter>
<letter id="A">
<journal ident="AACN CLINICAL ISSUES" abbrev="AACN Clin. Issues"></journal>
<journal ident="AACN CLINICAL ISSUES IN CRITICAL CARE NURSING" abbrev="AACN Clin. Issues Crit. Care Nurs."></journal>
<journal ident="AADE EDITORS JOURNAL" abbrev="AADE Ed. J."></journal>
<journal ident="AANA JOURNAL" abbrev="AANA J."></journal>
<journal ident="AANNT JOURNAL" abbrev="AANNT J."></journal>
<journal ident="AAOHN JOURNAL" abbrev="AAOHN J."></journal>
<journal ident="AAPG BULLETIN" abbrev="AAPG Bull."></journal>
<journal ident="AAPG MEMOIR" abbrev="AAPG Mem."></journal>
<journal ident="AAPPO JOURNAL" abbrev="AAPPO J."></journal>
<journal ident="AAPS JOURNAL" abbrev="AAPS J."></journal>
<journal ident="AAPS PHARMSCI" abbrev="AAPS PharmSci"></journal>
<journal ident="AARN NEWS LETTER" abbrev="AARN News Lett."></journal>
<journal ident="AATCC JOURNAL OF RESEARCH" abbrev="AATCC J. Res."></journal>
<journal ident="ABB REVIEW" abbrev="ABB Rev."></journal>
<journal ident="ABDOMINAL IMAGING" abbrev="Abdom. Imaging"></journal>
<journal ident="ABHANDLUNGEN AUS DEM MATHEMATISCHEN SEMINAR DER UNIVERSITAT HAMBURG" abbrev="Abh. Math. Semin. Univ. Hamburg"></journal>
<journal ident="ABHANDLUNGEN AUS DEM WESTFALISCHEN MUSEUM FUR NATURKUNDE" abbrev="Abh. Westfäl. Mus. Nat.Kd."></journal>
<journal ident="ABHANDLUNGEN DER AKADEMIE DER WISSENSCHAFTEN DER DDR" abbrev="Abh. Akad. Wiss. DDR"></journal>
<journal ident="ABHANDLUNGEN DER AKADEMIE DER WISSENSCHAFTEN DER DDR ABTEILUNG MATHEMATIK NATURWISSENSCHAFTEN TECHNIK" abbrev="Abh. Akad. Wiss. DDR, Abt. Math., Naturwiss., Tech."></journal>
<journal ident="ABHANDLUNGEN DER BRAUNSCHWEIGISCHEN WISSENSCHAFTLICHEN GESELLSCHAFT" abbrev="Abh. Braunschweig. Wiss. Ges."></journal>
<journal ident="ABHANDLUNGEN DER MATHEMATISCHNATURWISSENSCHAFTLICHEN KLASSE AKADEMIE DER WISSENSCHAFTEN UND DER LITERATUR IN MAINZ" abbrev="Abh. Math.-Naturwiss. Kl. Akad. Wiss. Lit. Mainz"></journal>
<journal ident="ABHANDLUNGEN DER NATURFORSCHENDEN GESELLSCHAFT IN ZURICH" abbrev="Abh. Nat.Forsch. Ges. Zür."></journal>
<journal ident="ABHANDLUNGEN DER SENCKENBERGISCHEN NATURFORSCHENDEN GESELLSCHAFT" abbrev="Abh. Senckenb. Naturforsch. Ges."></journal>
<journal ident="ABHANDLUNGEN DES NATURWISSENSCHAFTLICHEN VEREINS ZU BREMEN" abbrev="Abh. Nat.Wiss. Ver. Bremen"></journal>
<journal ident="ABNF JOURNAL" abbrev="ABNF J."></journal>
<journal ident="A BRADFORD BOOK" abbrev="Bradford Book"></journal>
<journal ident="ABSTRACTA BOTANICA" abbrev="Abstr. Bot."></journal>
<journal ident="ABSTRACT AND APPLIED ANALYSIS" abbrev="Abstr. Appl. Anal."></journal>
<journal ident="ABSTRACTS OF PAPERS PRESENTED TO THE AMERICAN MATHEMATICAL SOCIETY" abbrev="Abstracts Amer. Math. Soc."></journal>
<journal ident="ACADEMIA" abbrev="Academia"></journal>
<journal ident="ACADEMIAE SCIENTIARUM FENNICAE ANNALES MATHEMATICA DISSERTATIONES" abbrev="Ann. Acad. Sci. Fenn. Math. Diss."></journal>
<journal ident="ACADEMIA PERUANA DE CIRUGIA" abbrev="Acad. Peru. Cir."></journal>
<journal ident="ACADEMIC EMERGENCY MEDICINE" abbrev="Acad. Emerg. Med."></journal>
<journal ident="ACADEMIC FORENSIC PATHOLOGY" abbrev="Acad. Forensic Pathol."></journal>
<journal ident="ACADEMIC MEDICINE" abbrev="Acad. Med."></journal>
<journal ident="ACADEMIC NURSE" abbrev="Acad. Nurse"></journal>
<journal ident="ACADEMIC RADIOLOGY" abbrev="Acad. Radiol."></journal>
<journal ident="ACADEMIE ROYALE DE BELGIQUE BULLETIN DE LA CLASSE DES SCIENCES" abbrev="Acad. Roy. Belg. Bull. Cl. Sci."></journal>
<journal ident="ACADEMIE ROYALE DE BELGIQUE CLASSE DES SCIENCES MEMOIRES COLLECTION" abbrev="Acad. Roy. Belg. Cl. Sci. Mém. Collect."></journal>
<journal ident="ACADEMIE SERBE DES SCIENCES ET DES ARTS CLASSE DES SCIENCES MATHEMATIQUES ET NATURELLES BULLETIN" abbrev="Bull. Acad. Serbe Sci. Arts Cl. Sci. Math. Natur."></journal>
<journal ident="ACADEMIE SERBE DES SCIENCES ET DES ARTS GLAS" abbrev="Acad. Serbe Sci. Arts Glas"></journal>
<journal ident="ACADEMY OF MANAGEMENT JOURNAL" abbrev="Acad. Manage. J."></journal>
<journal ident="ACADEMY OF MANAGEMENT REVIEW" abbrev="Acad. Manage. Rev."></journal>
<journal ident="ACADEMY REVIEW OF THE CALIFORNIA ACADEMY OF PERIODONTOLOGY" abbrev="Acad. Rev. Calif. Acad. Periodontol."></journal>
<journal ident="ACAROLOGIA" abbrev="Acarologia"></journal>
<journal ident="ACA TRANSACTIONS" abbrev="ACA Trans."></journal>
<journal ident="ACCADEMIA DELLE SCIENZE DI TORINO MEMORIE CLASSE DI SCIENZE FISICHE MATEMATICHE E NATURALI" abbrev="Mem. Accad. Sci. Torino Cl. Sci. Fis. Mat. Natur."></journal>
<journal ident="ACCADEMIA NAZIONALE DELLE SCIENZE DETTA DEI XL RENDICONTI MEMORIE DI MATEMATICA E APPLICAZIONI" abbrev="Rend. Accad. Naz. Sci. XL Mem. Mat. Appl."></journal>
<journal ident="ACCES SCIENCES" abbrev="Accès Sci."></journal>
<journal ident="ACCESS MICROBIOLOGY" abbrev="Access Microbiol."></journal>
<journal ident="ACCIDENT ANALYSIS AND PREVENTION" abbrev="Accid. Anal. Prev."></journal>
<journal ident="ACCIDENT AND EMERGENCY NURSING" abbrev="Accid. Emerg. Nurs."></journal>
<journal ident="ACCOUNTS OF CHEMICAL RESEARCH" abbrev="Acc. Chem. Res."></journal>
<journal ident="ACCREDITATION AND QUALITY ASSURANCE" abbrev="Accredit. Qual. Assur."></journal>
<journal ident="ACHIEVEMENTS IN THE LIFE SCIENCES" abbrev="Achiev. Life Sci."></journal>
<journal ident="ACH MODELS IN CHEMISTRY" abbrev="ACH - Models Chem."></journal>
<journal ident="ACI MATERIALS JOURNAL" abbrev="ACI Mater. J."></journal>
<journal ident="ACI STRUCTURAL JOURNAL" abbrev="ACI Struct. J."></journal>
<journal ident="ACM COMPUTING SURVEYS" abbrev="ACM Comput. Surv."></journal>
<journal ident="ACM DIGITAL THREATS RESEARCH AND PRACTICE" abbrev="ACM Digital Threats: Res. Pract."></journal>
<journal ident="ACM DISTINGUISHED THESES" abbrev="ACM Disting. Theses"></journal>
<journal ident="ACM JOURNAL OF DATA AND INFORMATION QUALITY" abbrev="ACM J. Data Inf. Qual."></journal>
<journal ident="ACM JOURNAL OF EXPERIMENTAL ALGORITHMICS" abbrev="ACM J. Exp. Algorithmics"></journal>
<journal ident="ACM JOURNAL ON COMPUTING AND CULTURAL HERITAGE" abbrev="ACM J. Comput. Cult. Heritage"></journal>
<journal ident="ACM JOURNAL ON EMERGING TECHNOLOGIES IN COMPUTING" abbrev="ACM J. Emerging Technol. Comput."></journal>
<journal ident="ACM TRANSACTIONS ON ACCESSIBLE COMPUTING" abbrev="ACM Trans. Accessible Comput."></journal>
<journal ident="ACM TRANSACTIONS ON ALGORITHMS" abbrev="ACM Trans. Algorithms"></journal>
<journal ident="ACM TRANSACTIONS ON APPLIED PERCEPTION" abbrev="ACM Trans. Appl. Percept."></journal>
<journal ident="ACM TRANSACTIONS ON ARCHITECTURE AND CODE OPTIMIZATION" abbrev="ACM Trans. Archit. Code Optim."></journal>
<journal ident="ACM TRANSACTIONS ON ASIAN AND LOWRESOURCE LANGUAGE INFORMATION PROCESSING" abbrev="ACM Trans. Asian Low-Resour. Lang. Inf. Process."></journal>
<journal ident="ACM TRANSACTIONS ON ASIAN LANGUAGE INFORMATION PROCESSING" abbrev="ACM Trans. Asian Lang. Inf. Process."></journal>
<journal ident="ACM TRANSACTIONS ON AUTONOMOUS AND ADAPTIVE SYSTEMS" abbrev="ACM Trans. Auton. Adapt. Syst."></journal>
<journal ident="ACM TRANSACTIONS ON COMPUTATIONAL LOGIC" abbrev="ACM Trans. Comput. Logic"></journal>
<journal ident="ACM TRANSACTIONS ON COMPUTATION THEORY" abbrev="ACM Trans. Comput. Theory"></journal>
<journal ident="ACM TRANSACTIONS ON COMPUTERHUMAN INTERACTION" abbrev="ACM Trans. Comput.-Hum. Interact."></journal>
<journal ident="ACM TRANSACTIONS ON COMPUTER SYSTEMS" abbrev="ACM Trans. Comput. Syst."></journal>
<journal ident="ACM TRANSACTIONS ON COMPUTING EDUCATION" abbrev="ACM Trans. Comput. Educ."></journal>
<journal ident="ACM TRANSACTIONS ON DATABASE SYSTEMS" abbrev="ACM Trans. Database Syst."></journal>
<journal ident="ACM TRANSACTIONS ON DESIGN AUTOMATION OF ELECTRONIC SYSTEMS" abbrev="ACM Trans. Des. Autom. Electron. Syst."></journal>
<journal ident="ACM TRANSACTIONS ON ECONOMICS AND COMPUTATION" abbrev="ACM Trans. Econ. Comput."></journal>
<journal ident="ACM TRANSACTIONS ON EMBEDDED COMPUTING SYSTEMS" abbrev="ACM Trans. Embedded Comput. Syst."></journal>
<journal ident="ACM TRANSACTIONS ON GRAPHICS" abbrev="ACM Trans. Graphics"></journal>
<journal ident="ACM TRANSACTIONS ON INFORMATION AND SYSTEM SECURITY" abbrev="ACM Trans. Inf. Syst. Secur."></journal>
<journal ident="ACM TRANSACTIONS ON INFORMATION SYSTEMS" abbrev="ACM Trans. Inf. Syst."></journal>
<journal ident="ACM TRANSACTIONS ON INTELLIGENT SYSTEMS AND TECHNOLOGY" abbrev="ACM Trans. Intell. Syst. Technol."></journal>
<journal ident="ACM TRANSACTIONS ON INTERACTIVE INTELLIGENT SYSTEMS" abbrev="ACM Trans. Interact. Intell. Syst."></journal>
<journal ident="ACM TRANSACTIONS ON INTERNET TECHNOLOGY" abbrev="ACM Trans. Internet Technol."></journal>
<journal ident="ACM TRANSACTIONS ON KNOWLEDGE DISCOVERY FROM DATA" abbrev="ACM Trans. Knowl. Discovery Data"></journal>
<journal ident="ACM TRANSACTIONS ON MANAGEMENT INFORMATION SYSTEMS" abbrev="ACM Trans. Manage. Inf. Syst."></journal>
<journal ident="ACM TRANSACTIONS ON MATHEMATICAL SOFTWARE" abbrev="ACM Trans. Math. Software"></journal>
<journal ident="ACM TRANSACTIONS ON MODELING AND COMPUTER SIMULATION" abbrev="ACM Trans. Model. Comput. Simul."></journal>
<journal ident="ACM TRANSACTIONS ON MULTIMEDIA COMPUTING COMMUNICATIONS AND APPLICATIONS" abbrev="ACM Trans. Multimedia Comput. Commun. Appl."></journal>
<journal ident="ACM TRANSACTIONS ON PARALLEL COMPUTING" abbrev="ACM Trans. Parallel Comput."></journal>
<journal ident="ACM TRANSACTIONS ON PROGRAMMING LANGUAGES AND SYSTEMS" abbrev="ACM Trans. Program. Lang. Syst."></journal>
<journal ident="ACM TRANSACTIONS ON RECONFIGURABLE TECHNOLOGY AND SYSTEMS" abbrev="ACM Trans. Reconfigurable Technol. Syst."></journal>
<journal ident="ACM TRANSACTIONS ON SENSOR NETWORKS" abbrev="ACM Trans. Sens. Netw."></journal>
<journal ident="ACM TRANSACTIONS ON SOFTWARE ENGINEERING AND METHODOLOGY" abbrev="ACM Trans. Software Eng. Method."></journal>
<journal ident="ACM TRANSACTIONS ON SPEECH AND LANGUAGE PROCESSING" abbrev="ACM Trans. Speech Lang. Process."></journal>
<journal ident="ACM TRANSACTIONS ON STORAGE" abbrev="ACM Trans. Storage"></journal>
<journal ident="ACM TRANSACTIONS ON THE WEB" abbrev="ACM Trans. Web"></journal>
<journal ident="ACOUSTICAL IMAGING" abbrev="Acoust. Imaging"></journal>
<journal ident="ACOUSTICAL PHYSICS" abbrev="Acoust. Phys."></journal>
<journal ident="ACOUSTICAL SCIENCE AND TECHNOLOGY" abbrev="Acoust. Sci. Technol."></journal>
<journal ident="ACOUSTICS RESEARCH LETTERS ONLINE" abbrev="Acoust. Res. Lett. Online"></journal>
<journal ident="ACOUSTICS TODAY" abbrev="Acoust. Today"></journal>
<journal ident="ACP JOURNAL CLUB" abbrev="ACP J. Club"></journal>
<journal ident="ACQUISITIONS MEDICALES RECENTES" abbrev="Acquis. Méd. Récent."></journal>
<journal ident="ACRH REPORTS" abbrev="ACRH Rep."></journal>
<journal ident="ACROSS THE BOARD" abbrev="Across Board"></journal>
<journal ident="ACS APPLIED BIO MATERIALS" abbrev="ACS Appl. Bio Mater."></journal>
<journal ident="ACS APPLIED ELECTRONIC MATERIALS" abbrev="ACS Appl. Electron. Mater."></journal>
<journal ident="ACS APPLIED ENERGY MATERIALS" abbrev="ACS Appl. Energy Mater."></journal>
<journal ident="ACS APPLIED MATERIALS INTERFACES" abbrev="ACS Appl. Mater. Interfaces"></journal>
<journal ident="ACS APPLIED NANO MATERIALS" abbrev="ACS Appl. Nano Mater."></journal>
<journal ident="ACS APPLIED POLYMER MATERIALS" abbrev="ACS Appl. Polym. Mater."></journal>
<journal ident="ACS BIOMATERIALS SCIENCE ENGINEERING" abbrev="ACS Biomater. Sci. Eng."></journal>
<journal ident="ACS CATALYSIS" abbrev="ACS Catal."></journal>
<journal ident="ACS CENTRAL SCIENCE" abbrev="ACS Cent. Sci."></journal>
<journal ident="ACS CHEMICAL BIOLOGY" abbrev="ACS Chem. Biol."></journal>
<journal ident="ACS CHEMICAL HEALTH AND SAFETY" abbrev="ACS Chem. Health Saf."></journal>
<journal ident="ACS CHEMICAL NEUROSCIENCE" abbrev="ACS Chem. Neurosci."></journal>
<journal ident="ACS COMBINATORIAL SCIENCE" abbrev="ACS Comb. Sci."></journal>
<journal ident="ACS EARTH AND SPACE CHEMISTRY" abbrev="ACS Earth Space Chem."></journal>
<journal ident="ACS ENERGY LETTERS" abbrev="ACS Energy Lett."></journal>
<journal ident="ACS ES AND T ENGINEERING" abbrev="ACS ES &amp; T Eng."></journal>
<journal ident="ACS ES AND T WATER" abbrev="ACS ES &amp; T Water"></journal>
<journal ident="ACS INFECTIOUS DISEASES" abbrev="ACS Infect. Dis."></journal>
<journal ident="ACS MACRO LETTERS" abbrev="ACS Macro Lett."></journal>
<journal ident="ACS MATERIALS LETTERS" abbrev="ACS Mater. Lett."></journal>
<journal ident="ACS MEDICINAL CHEMISTRY LETTERS" abbrev="ACS Med. Chem. Lett."></journal>
<journal ident="ACS NANO" abbrev="ACS Nano"></journal>
<journal ident="ACS OMEGA" abbrev="ACS Omega"></journal>
<journal ident="ACS PHARMACOLOGY TRANSLATIONAL SCIENCE" abbrev="ACS Pharmacol. Transl. Sci."></journal>
<journal ident="ACS PHOTONICS" abbrev="ACS Photonics"></journal>
<journal ident="ACS SENSORS" abbrev="ACS Sens."></journal>
<journal ident="ACS SUSTAINABLE CHEMISTRY ENGINEERING" abbrev="ACS Sustainable Chem. Eng."></journal>
<journal ident="ACS SYMPOSIUM SERIES" abbrev="ACS Symp. Ser."></journal>
<journal ident="ACS SYNTHETIC BIOLOGY" abbrev="ACS Synth. Biol."></journal>
<journal ident="ACTA ACADEMIAE ABOENSIS SERIES B" abbrev="Acta Acad. Abo. Ser. B"></journal>
<journal ident="ACTA ACADEMIAE MEDICINAE WUHAN" abbrev="Acta Acad. Med. Wuhan"></journal>
<journal ident="ACTA ACUSTICA" abbrev="Acta Acust."></journal>
<journal ident="ACTA ACUSTICA UNITED WITH ACUSTICA" abbrev="Acta Acust. United Acust."></journal>
<journal ident="ACTA AGRALIA FENNICA" abbrev="Acta Agral. Fenn."></journal>
<journal ident="ACTA AGRARIA ET SILVESTRIA SERIA LESNA KRAKAU" abbrev="Acta Agrar. Silv., Ser. Lesn."></journal>
<journal ident="ACTA AGRICULTURAE SCANDINAVICA SECTION A ANIMAL SCIENCE" abbrev="Acta Agric. Scand. Sect. A"></journal>
<journal ident="ACTA AGRICULTURAE SCANDINAVICA SECTION B SOIL AND PLANT SCIENCE" abbrev="Acta Agric. Scand. Sect. B"></journal>
<journal ident="ACTA ALLERGOLOGICA" abbrev="Acta Allergol."></journal>
<journal ident="ACTA ANAESTHESIOLOGICA" abbrev="Acta Anaesthesiol."></journal>
<journal ident="ACTA ANAESTHESIOLOGICA BELGICA" abbrev="Acta Anaesthesiol. Belg."></journal>
<journal ident="ACTA ANAESTHESIOLOGICA SCANDINAVICA" abbrev="Acta Anaesthesiol. Scand."></journal>
<journal ident="ACTA ANAESTHESIOLOGICA SCANDINAVICA SUPPLEMENTUM" abbrev="Acta Anaesthesiol. Scand. Suppl."></journal>
<journal ident="ACTA ANAESTHESIOLOGICA SINICA" abbrev="Acta Anaesthesiol. Sin."></journal>
<journal ident="ACTA ANAESTHESIOLOGICA TAIWANICA" abbrev="Acta Anaesthesiol. Taiwan."></journal>
<journal ident="ACTA ANATOMICA" abbrev="Acta Anat."></journal>
<journal ident="ACTA ANATOMICA SUPPLEMENT" abbrev="Acta Anat. Suppl."></journal>
<journal ident="ACTA ANTHROPOGENETICA" abbrev="Acta Anthropogenet."></journal>
<journal ident="ACTA APPLICANDAE MATHEMATICAE" abbrev="Acta Appl. Math."></journal>
<journal ident="ACTA ARCHAEOLOGICA" abbrev="Acta Archaeol."></journal>
<journal ident="ACTA ARITHMETICA" abbrev="Acta Arith."></journal>
<journal ident="ACTA ASTRONAUTICA" abbrev="Acta Astronaut."></journal>
<journal ident="ACTA ASTRONOMICA SINICA" abbrev="Acta Astronom. Sinica"></journal>
<journal ident="ACTA ASTROPHYSICA SINICA" abbrev="Acta Astrophys. Sinica"></journal>
<journal ident="ACTA AUTOMATICA SINICA" abbrev="Acta Autom. Sin."></journal>
<journal ident="ACTA BELGICA MEDICA PHYSICA" abbrev="Acta Belg. Med. Phys."></journal>
<journal ident="ACTA BERNENSIA" abbrev="Acta Bern."></journal>
<journal ident="ACTA BIOCHIMICA ET BIOPHYSICA ACADEMIAE SCIENTIARUM HUNGARICAE" abbrev="Acta Biochim. Biophys. Acad. Sci. Hung."></journal>
<journal ident="ACTA BIOCHIMICA ET BIOPHYSICA HUNGARICA" abbrev="Acta Biochim. Biophys. Hung."></journal>
<journal ident="ACTA BIOCHIMICA ET BIOPHYSICA SINICA" abbrev="Acta Biochim. Biophys. Sin."></journal>
<journal ident="ACTA BIOCHIMICA POLONICA" abbrev="Acta Biochim. Pol."></journal>
<journal ident="ACTA BIOLOGIAE EXPERIMENTALIS" abbrev="Acta Biol. Exp."></journal>
<journal ident="ACTA BIOLOGICA ACADEMIAE SCIENTIARUM HUNGARICAE" abbrev="Acta Biol. Acad. Sci. Hung."></journal>
<journal ident="ACTA BIOLOGICA ET MEDICA" abbrev="Acta Biol. Med."></journal>
<journal ident="ACTA BIOLOGICA ET MEDICA GERMANICA" abbrev="Acta Biol. Med. Ger."></journal>
<journal ident="ACTA BIOLOGICA HUNGARICA" abbrev="Acta Biol. Hung."></journal>
<journal ident="ACTA BIOLOGICA MONTANA" abbrev="Acta Biol. Mont."></journal>
<journal ident="ACTA BIOMATERIALIA" abbrev="Acta Biomater."></journal>
<journal ident="ACTA BIOMEDICA DE LATENEO PARMENSE" abbrev="Acta Biomed. Ateneo Parmense"></journal>
<journal ident="ACTA BIOQUIMICA CLINICA LATINOAMERICANA" abbrev="Acta Bioquim. Clin. Latinoam."></journal>
<journal ident="ACTA BIOTECHNOLOGICA" abbrev="Acta Biotechnol."></journal>
<journal ident="ACTA BIOTHEORETICA" abbrev="Acta Biotheor."></journal>
<journal ident="ACTA BOTANICA ACADEMIAE SCIENTIARUM HUNGARICAE" abbrev="Acta Bot. Acad. Sci. Hung."></journal>
<journal ident="ACTA BOTANICA FENNICA" abbrev="Acta Bot. Fenn."></journal>
<journal ident="ACTA BOTANICA HUNGARICA" abbrev="Acta Bot. Hung."></journal>
<journal ident="ACTA CANCEROLOGICA" abbrev="Acta Cancerol."></journal>
<journal ident="ACTA CARDIOLOGICA" abbrev="Acta Cardiol."></journal>
<journal ident="ACTA CARDIOLOGICA SUPPLEMENTUM" abbrev="Acta Cardiol. Suppl."></journal>
<journal ident="ACTA CHEMICA SCANDINAVICA" abbrev="Acta Chem. Scand."></journal>
<journal ident="ACTA CHEMICA SCANDINAVICA SERIES A PHYSICAL AND INORGANIC CHEMISTRY" abbrev="Acta Chem. Scand. Ser. A"></journal>
<journal ident="ACTA CHEMICA SCANDINAVICA SERIES B ORGANIC CHEMISTRY AND BIOCHEMISTRY" abbrev="Acta Chem. Scand. Ser. B"></journal>
<journal ident="ACTA CHIMICA HUNGARICA" abbrev="Acta Chim. Hung."></journal>
<journal ident="ACTA CHIMICA SINICA" abbrev="Acta Chim. Sinica"></journal>
<journal ident="ACTA CHIMICA SLOVACA" abbrev="Acta Chim. Slovaca"></journal>
<journal ident="ACTA CHIMICA SLOVENICA" abbrev="Acta Chim. Slov."></journal>
<journal ident="ACTA CHIRURGIAE ORTHOPAEDICAE ET TRAUMATOLOGIAE CECHOSLOVACA" abbrev="Acta Chir. Orthop. Traumatol. Cech."></journal>
<journal ident="ACTA CHIRURGIAE PLASTICAE" abbrev="Acta Chir. Plast."></journal>
<journal ident="ACTA CHIRURGICA ACADEMIAE SCIENTIARUM HUNGARICAE" abbrev="Acta Chir. Acad. Sci. Hung."></journal>
<journal ident="ACTA CHIRURGICA BELGICA" abbrev="Acta Chir. Belg."></journal>
<journal ident="ACTA CHIRURGICA HUNGARICA" abbrev="Acta Chir. Hung."></journal>
<journal ident="ACTA CHIRURGICA ITALICA" abbrev="Acta Chir. Ital."></journal>
<journal ident="ACTA CHIRURGICA IUGOSLAVICA" abbrev="Acta Chir. Iugosl."></journal>
<journal ident="ACTA CHIRURGICA SCANDINAVICA" abbrev="Acta Chir. Scand."></journal>
<journal ident="ACTA CHIRURGICA SCANDINAVICA SUPPLEMENTUM" abbrev="Acta Chir. Scand. Suppl."></journal>
<journal ident="ACTA CHROMATOGRAPHICA" abbrev="Acta Chromatogr."></journal>
<journal ident="ACTA CIENCIA INDICA CHEMISTRY" abbrev="Acta Cienc. Indica, Chem."></journal>
<journal ident="ACTA CIENCIA INDICA MATHEMATICS" abbrev="Acta Cienc. Indica Math."></journal>
<journal ident="ACTA CIENCIA INDICA PHYSICS" abbrev="Acta Cienc. Indica, Phys."></journal>
<journal ident="ACTA CIENTIFICA VENEZOLANA" abbrev="Acta Cient. Venez."></journal>
<journal ident="ACTA CLINICA BELGICA" abbrev="Acta Clin. Belg."></journal>
<journal ident="ACTA CLINICA BELGICA SUPPLEMENTUM" abbrev="Acta Clin. Belg. Suppl."></journal>
<journal ident="ACTA CLINICA ODONTOLOGICA" abbrev="Acta Clin. Odontol."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA" abbrev="Acta Crystallogr."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION A CRYSTAL PHYSICS DIFFRACTION THEORETICAL AND GENERAL CRYSTALLOGRAPHY" abbrev="Acta Crystallogr. A"></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION A FOUNDATIONS" abbrev="Acta Crystallogr., Sect. A: Found."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION A FOUNDATIONS AND ADVANCES" abbrev="Acta Crystallogr., Sect. A: Found. Adv."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION A FOUNDATIONS OF CRYSTALLOGRAPHY" abbrev="Acta Crystallogr., Sect. A: Found. Crystallogr."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION B STRUCTURAL CRYSTALLOGRAPHY AND CRYSTAL CHEMISTRY" abbrev="Acta Crystallogr. B"></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION B STRUCTURAL SCIENCE" abbrev="Acta Crystallogr., Sect. B: Struct. Sci."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION B STRUCTURAL SCIENCE CRYSTAL ENGINEERING AND MATERIALS" abbrev="Acta Crystallogr., Sect. B: Struct. Sci., Cryst. Eng. Mater."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION C CRYSTAL STRUCTURE COMMUNICATIONS" abbrev="Acta Crystallogr., Sect. C: Cryst. Struct. Commun."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION C STRUCTURAL CHEMISTRY" abbrev="Acta Crystallogr., Sect. C: Struct. Chem."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION D BIOLOGICAL CRYSTALLOGRAPHY" abbrev="Acta Crystallogr., Sect. D: Biol. Crystallogr."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION E CRYSTALLOGRAPHIC COMMUNICATIONS" abbrev="Acta Crystallogr., Sect. E: Crystallogr. Commun."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION E STRUCTURE REPORTS ONLINE" abbrev="Acta Crystallogr., Sect. E: Struct. Rep. Online"></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION F STRUCTURAL BIOLOGY AND CRYSTALLIZATION COMMUNICATIONS" abbrev="Acta Crystallogr., Sect. F: Struct. Biol. Cryst. Commun."></journal>
<journal ident="ACTA CRYSTALLOGRAPHICA SECTION F STRUCTURAL BIOLOGY COMMUNICATIONS" abbrev="Acta Crystallogr., Sect. F: Struct. Biol. Commun."></journal>
<journal ident="ACTA CYBERNETICA" abbrev="Acta Cybernet."></journal>
<journal ident="ACTA CYTOLOGICA" abbrev="Acta Cytol."></journal>
<journal ident="ACTA DE ODONTOLOGIA PEDIATRICA" abbrev="Acta Odontol. Pediatr."></journal>
<journal ident="ACTA DERMATOLOGICA KYOTO ENGLISH EDITION" abbrev="Acta Dermatol. Kyoto Engl. Ed."></journal>
<journal ident="ACTA DERMATO VENEREOLOGICA" abbrev="Acta Derm. Venereol."></journal>
<journal ident="ACTA DERMATO VENEREOLOGICA SUPPLEMENTUM" abbrev="Acta Derm. Venereol. Suppl."></journal>
<journal ident="ACTA DIABETOLOGICA" abbrev="Acta Diabetol."></journal>
<journal ident="ACTA DIABETOLOGICA LATINA" abbrev="Acta Diabetol. Lat."></journal>
<journal ident="ACTA EMBRYOLOGIAE ET MORPHOLOGIAE EXPERIMENTALIS" abbrev="Acta Embryol. Morphol. Exp."></journal>
<journal ident="ACTA EMBRYOLOGIAE EXPERIMENTALIS" abbrev="Acta Embryol. Exp."></journal>
<journal ident="ACTA ENDOCRINOLOGICA" abbrev="Acta Endocrinol."></journal>
<journal ident="ACTA ENDOCRINOLOGICA SUPPLEMENTUM" abbrev="Acta Endocrinol. Suppl."></journal>
<journal ident="ACTA EUROPAEA FERTILITATIS" abbrev="Acta Eur. Fertil."></journal>
<journal ident="ACTA FARMACEUTICA BONAERENSE" abbrev="Acta Farm. Bonaerense"></journal>
<journal ident="ACTA FORESTALIA FENNICA" abbrev="Acta For. Fenn."></journal>
<journal ident="ACTA GASTROENTEROLOGICA BELGICA" abbrev="Acta Gastroenterol. Belg."></journal>
<journal ident="ACTA GASTROENTEROLOGICA LATINOAMERICANA" abbrev="Acta Gastroenterol. Latinoam."></journal>
<journal ident="ACTA GENETICAE MEDICAE ET GEMELLOLOGIAE" abbrev="Acta Genet. Med. Gemellol."></journal>
<journal ident="ACTA GENETICA ET STATISTICA MEDICA" abbrev="Acta Genet. Stat. Med."></journal>
<journal ident="ACTA GEODAETICA ET GEOPHYSICA" abbrev="Acta Geod. Geophys."></journal>
<journal ident="ACTA GEODYNAMICS ET GEOMATERIALIA" abbrev="Acta Geodyn. Geomater."></journal>
<journal ident="ACTA GEOGRAPHICA SINICA" abbrev="Acta Geogr. Sin."></journal>
<journal ident="ACTA GEOLOGICA SINICA" abbrev="Acta Geol. Sin."></journal>
<journal ident="ACTA GEOPHYSICA" abbrev="Acta Geophys."></journal>
<journal ident="ACTA GEOTECHNICA" abbrev="Acta Geotech."></journal>
<journal ident="ACTA GERONTOLOGICA" abbrev="Acta Gerontol."></journal>
<journal ident="ACTA GINECOLOGICA" abbrev="Acta Ginecol."></journal>
<journal ident="ACTA GYNAECOLOGICA ET OBSTETRICA HISPANOLUSITANA" abbrev="Acta Gynaecol. Obstet. Hisp. Lusit."></journal>
<journal ident="ACTA HAEMATOLOGICA" abbrev="Acta Haematol."></journal>
<journal ident="ACTA HAEMATOLOGICA POLONICA" abbrev="Acta Haematol. Pol."></journal>
<journal ident="ACTA HEPATOGASTROENTEROLOGICA" abbrev="Acta Hepatogastroenterol."></journal>
<journal ident="ACTA HEPATOSPLENOLOGICA" abbrev="Acta Hepatosplenol."></journal>
<journal ident="ACTA HISTOCHEMICA" abbrev="Acta Histochem."></journal>
<journal ident="ACTA HISTOCHEMICA SUPPLEMENTBAND" abbrev="Acta Histochem. Suppl."></journal>
<journal ident="ACTA HISTORICA LEOPOLDINA" abbrev="Acta Hist. Leopold."></journal>
<journal ident="ACTA HISTORICA SCIENTIARUM NATURALIUM ET MEDICINALIUM" abbrev="Acta Hist. Sci. Nat. Med."></journal>
<journal ident="ACTA HORTICULTURAE" abbrev="Acta Hortic."></journal>
<journal ident="ACTA HOSPITALIA" abbrev="Acta Hosp."></journal>
<journal ident="ACTA HYDROCHIMICA ET HYDROBIOLOGICA" abbrev="Acta Hydroch. Hydrob."></journal>
<journal ident="ACTA HYDROPHYSICA" abbrev="Acta Hydrophys."></journal>
<journal ident="ACTA IBERICA RADIOLOGICA CANCEROLOGICA" abbrev="Acta Iber. Radiol. Cancerol."></journal>
<journal ident="ACTA INFORMATICA" abbrev="Acta Inform."></journal>
<journal ident="ACTA INSTITUTI FORESTALIS ZVOLENENSIS" abbrev="Acta Inst. For. Zvolen."></journal>
<journal ident="ACTA ISOTOPICA" abbrev="Acta Isot."></journal>
<journal ident="ACTA JUTLANDICA" abbrev="Acta Jutl."></journal>
<journal ident="ACTA LEIDENSIA" abbrev="Acta Leiden."></journal>
<journal ident="ACTA LEPROLOGICA" abbrev="Acta Leprol."></journal>
<journal ident="ACTA MATERIALIA" abbrev="Acta Mater."></journal>
<journal ident="ACTA MATHEMATICA" abbrev="Acta Math."></journal>
<journal ident="ACTA MATHEMATICAE APPLICATAE SINICA" abbrev="Acta Math. Appl. Sinica"></journal>
<journal ident="ACTA MATHEMATICA ET INFORMATICA UNIVERSITATIS OSTRAVIENSIS" abbrev="Acta Math. Inform. Univ. Ostraviensis"></journal>
<journal ident="ACTA MATHEMATICA HUNGARICA" abbrev="Acta Math. Hungar."></journal>
<journal ident="ACTA MATHEMATICA SCIENTIA CHINESE" abbrev="Acta Math. Sci. (Chinese)"></journal>
<journal ident="ACTA MATHEMATICA SCIENTIA ENGLISH" abbrev="Acta Math. Sci. (English)"></journal>
<journal ident="ACTA MATHEMATICA SINICA" abbrev="Acta Math. Sinica"></journal>
<journal ident="ACTA MATHEMATICA UNIVERSITATIS COMENIANAE NEW SERIES" abbrev="Acta Math. Univ. Comenian. (N.S.)"></journal>
<journal ident="ACTA MATHEMATICA VIETNAMICA" abbrev="Acta Math. Vietnam."></journal>
<journal ident="ACTA MECHANICA" abbrev="Acta Mech."></journal>
<journal ident="ACTA MECHANICA SINICA" abbrev="Acta Mech. Sin."></journal>
<journal ident="ACTA MECHANICA SOLIDA SINICA" abbrev="Acta Mech. Solida Sin."></journal>
<journal ident="ACTA MEDICA" abbrev="Acta Medica"></journal>
<journal ident="ACTA MEDICA ACADEMIAE SCIENTIARUM HUNGARICAE" abbrev="Acta Med. Acad. Sci. Hung."></journal>
<journal ident="ACTA MEDICA AUSTRIACA" abbrev="Acta Med. Austriaca"></journal>
<journal ident="ACTA MEDICA AUSTRIACA SUPPLEMENT" abbrev="Acta Med. Austriac. Suppl."></journal>
<journal ident="ACTA MEDICA COSTARRICENSE" abbrev="Acta Méd. Costarric."></journal>
<journal ident="ACTA MEDICA CROATICA" abbrev="Acta Med. Croatica"></journal>
<journal ident="ACTA MEDICA ET BIOLOGICA" abbrev="Acta Med. Biol."></journal>
<journal ident="ACTA MEDICA HUNGARICA" abbrev="Acta Med. Hung."></journal>
<journal ident="ACTA MEDICA IRANICA" abbrev="Acta Med. Iran."></journal>
<journal ident="ACTA MEDICA ITALICA DI MEDICINA TROPICALE E SUBTROPICALE E DI GASTROENTEROLOGIA" abbrev="Acta Med. Ital. Med. Trop. Subtrop. Gastroenterol."></journal>
<journal ident="ACTA MEDICA IUGOSLAVICA" abbrev="Acta Med. Iugosl."></journal>
<journal ident="ACTA MEDICA NAGASAKIENSIA" abbrev="Acta Med. Nagasaki."></journal>
<journal ident="ACTA MEDICA OKAYAMA" abbrev="Acta Med. Okayama"></journal>
<journal ident="ACTA MEDICA PHILIPPINA" abbrev="Acta Med. Philipp."></journal>
<journal ident="ACTA MEDICA POLONA" abbrev="Acta Med. Pol."></journal>
<journal ident="ACTA MEDICA PORTUGUESA" abbrev="Acta Med. Port."></journal>
<journal ident="ACTA MEDICA SCANDINAVICA" abbrev="Acta Med. Scand."></journal>
<journal ident="ACTA MEDICA SCANDINAVICA SUPPLEMENTUM" abbrev="Acta Med. Scand. Suppl."></journal>
<journal ident="ACTA MEDICA SUPPLEMENTUM" abbrev="Acta Medica Suppl."></journal>
<journal ident="ACTA MEDICA VETERINARIA" abbrev="Acta Med. Vet."></journal>
<journal ident="ACTA MEDICINAE LEGALIS ET SOCIALIS" abbrev="Acta Med. Leg. Soc."></journal>
<journal ident="ACTA METALLURGICA" abbrev="Acta Metall."></journal>
<journal ident="ACTA METALLURGICA ET MATERIALIA" abbrev="Acta Metall. Mater."></journal>
<journal ident="ACTA METALLURGICA SINICA" abbrev="Acta Metall. Sinica"></journal>
<journal ident="ACTA MICROBIOLOGICA ACADEMIAE SCIENTIARUM HUNGARICAE" abbrev="Acta Microbiol. Acad. Sci. Hung."></journal>
<journal ident="ACTA MICROBIOLOGICA BULGARICA" abbrev="Acta Microbiol. Bulg."></journal>
<journal ident="ACTA MICROBIOLOGICA ET IMMUNOLOGICA HUNGARICA" abbrev="Acta Microbiol. Immunol. Hung."></journal>
<journal ident="ACTA MICROBIOLOGICA HUNGARICA" abbrev="Acta Microbiol. Hung."></journal>